function report = install_ped_codex_patch_v3(project_root)
% INSTALL_PED_CODEX_PATCH_V3  Backup-then-install the corrected overlay.
% Run only after the currently running MATLAB pipeline has been stopped.
if nargin<1 || isempty(project_root); project_root='C:\Drive E\VsPredict_NRR_v5'; end
patch_root=fileparts(mfilename('fullpath'));
assert(isfolder(project_root) && isfile(fullfile(project_root,'main_nrr_pipeline.m')), ...
    'Installer: invalid VsPredict_NRR_v5 project root');
assert(~strcmpi(patch_root,project_root), ...
    'Installer: patch package and target project must be separate');

files={ ...
    'main_nrr_pipeline.m'; ...
    'run_ped_corrected_pipeline.m'; ...
    'run_reproducibility_check.m'; ...
    'selftest_ped_codex_patch_v3.m'; ...
    fullfile('+nrr_data','depth_segment_ids.m'); ...
    fullfile('+nrr_models','fit_cnn1d.m'); ...
    fullfile('+nrr_models','predict_cnn1d.m'); ...
    fullfile('+nrr_models','fit_base_set.m'); ...
    fullfile('+nrr_models','predict_base_set.m'); ...
    fullfile('+nrr_models','generate_inner_oof.m'); ...
    fullfile('+nrr_models','tune_inner_stacked.m'); ...
    fullfile('+nrr_eval','run_nested_cv.m'); ...
    fullfile('+nrr_eval','fit_frozen_deployment.m'); ...
    fullfile('+nrr_eval','predict_frozen_deployment.m'); ...
    fullfile('+nrr_eval','gate9_provenance.m'); ...
    fullfile('+nrr_eval','gate10_canonical_hp.m'); ...
    fullfile('+nrr_eval','gate12_primary_blind.m'); ...
    fullfile('+nrr_eval','gate13_direct_ridge.m'); ...
    fullfile('+nrr_eval','gate17_geomech_freeze.m')};

stamp=char(datetime('now','Format','yyyyMMdd_HHmmss'));
backup_root=fullfile(project_root,'patch_backups',['ped_codex_v3_' stamp]);
mkdir(backup_root); rows=cell(numel(files),6);
for i=1:numel(files)
    rel=files{i}; src=fullfile(patch_root,rel); dst=fullfile(project_root,rel);
    assert(isfile(src),'Installer: patch source missing: %s',rel);
    old_hash="NEW_FILE";
    if isfile(dst)
        old_hash=file_sha256(dst); backup=fullfile(backup_root,rel);
        ensure_parent(backup); [ok,msg]=copyfile(dst,backup);
        assert(ok,'Installer: backup failed for %s: %s',rel,msg);
    end
    ensure_parent(dst); [ok,msg]=copyfile(src,dst,'f');
    assert(ok,'Installer: copy failed for %s: %s',rel,msg);
    source_hash=file_sha256(src); installed_hash=file_sha256(dst);
    assert(strcmpi(source_hash,installed_hash), ...
        'Installer: post-copy hash mismatch for %s',rel);
    rows(i,:)={string(rel),old_hash,source_hash,installed_hash,"INSTALLED",string(dst)};
end
T=cell2table(rows,'VariableNames',{'RELATIVE_PATH','PREVIOUS_SHA256', ...
    'PATCH_SHA256','INSTALLED_SHA256','STATUS','DESTINATION'});
writetable(T,fullfile(backup_root,'INSTALL_MANIFEST.csv'));
report=struct('status','PASS','n_files',numel(files), ...
    'project_root',project_root,'backup_root',backup_root,'manifest',T);
fprintf('PED Codex patch v3 installed: %d files\nBackup: %s\n', ...
    numel(files),backup_root);
fprintf('Close MATLAB, start a clean session, then run self-tests.\n');
end

function ensure_parent(fp)
p=fileparts(fp); if ~isfolder(p); mkdir(p); end
end

function h=file_sha256(fp)
[rc,out]=system(sprintf('certutil -hashfile "%s" SHA256',fp));
assert(rc==0,'Installer: certutil failed for %s',fp);
t=regexp(lower(out),'[a-f0-9]{64}','match');
assert(~isempty(t),'Installer: SHA-256 parse failed for %s',fp);
h=string(t{1});
end
