function result = make_fig03_nested_cv(canon_run_folder, out_dir)
% MAKE_FIG03_NESTED_CV  True nested depth-blocked CV performance.
% Values are read directly from the frozen canonical fold table.

if nargin < 1
    canon_run_folder = fullfile(nrr_project_root(),'runs','run_20260903_155408');
end
if nargin < 2
    out_dir = fullfile(nrr_project_root(),'figures_final');
end

nrr_figure_style();
D = nrr_load_canonical(canon_run_folder);
nrr_assert_canonical(D);

T = D.cv_fold;
required = {'r2','rmse','n','FOLD'};
for k = 1:numel(required)
    assert(any(strcmpi(T.Properties.VariableNames,required{k})), ...
        'FIG03: missing canonical column %s',required{k});
end
r2_name   = T.Properties.VariableNames{strcmpi(T.Properties.VariableNames,'r2')};
rmse_name = T.Properties.VariableNames{strcmpi(T.Properties.VariableNames,'rmse')};
n_name    = T.Properties.VariableNames{strcmpi(T.Properties.VariableNames,'n')};
fold_name = T.Properties.VariableNames{strcmpi(T.Properties.VariableNames,'FOLD')};

T = sortrows(T,fold_name);
r2 = T.(r2_name);
rmse = T.(rmse_name);
nfold = T.(n_name);
fold_id = T.(fold_name);

assert(height(T)==5 && isequal(fold_id(:),(1:5)'), ...
    'FIG03: expected five ordered outer folds');
assert(isequal(nfold(:),[78;78;78;78;80]), ...
    'FIG03: canonical fold sizes mismatch');
assert(sum(nfold)==D.nDev && D.nDev==392, ...
    'FIG03: fold sizes must sum to 392');
assert(abs(D.cvPooledR2-0.6632)<5e-5);
assert(abs(D.cvPooledRMSE-0.0565)<5e-5);
assert(abs(D.cvMeanR2-0.5526)<5e-5);
assert(abs(D.cvSdR2-0.1246)<5e-5);

c = nrr_colors();
fig = figure('Units','centimeters','Visible','off', ...
    'Position',[0 0 17.4 8.6],'Color','white');
tl = tiledlayout(fig,1,2,'TileSpacing','compact','Padding','compact');

labels = arrayfun(@(f,n)sprintf('Fold %d (n=%d)',f,n), ...
    fold_id,nfold,'UniformOutput',false);

% Panel a: R-squared
ax1 = nexttile(tl,1);
bar(ax1,fold_id,r2,0.62,'FaceColor',c.wellA, ...
    'EdgeColor',[0.12 0.25 0.36],'LineWidth',0.45);
hold(ax1,'on');
yline(ax1,D.cvPooledR2,'--','Color',[0.25 0.25 0.25], ...
    'LineWidth',1.0);
text(ax1,fold_id,r2+0.014,compose('%.4f',r2), ...
    'HorizontalAlignment','center','VerticalAlignment','bottom', ...
    'FontSize',7.2,'FontWeight','bold','Interpreter','none');
text(ax1,0.58,D.cvPooledR2-0.018, ...
    sprintf('pooled R² = %.4f',D.cvPooledR2), ...
    'HorizontalAlignment','left','VerticalAlignment','top', ...
    'FontSize',7.0,'Color',[0.20 0.20 0.20], ...
    'BackgroundColor','white','Margin',1.5,'Interpreter','none');
text(ax1,0.58,0.795, ...
    sprintf('mean fold R² = %.4f ± %.4f',D.cvMeanR2,D.cvSdR2), ...
    'HorizontalAlignment','left','VerticalAlignment','top', ...
    'FontSize',6.8,'Color',[0.20 0.20 0.20], ...
    'BackgroundColor','white','Margin',1.5,'Interpreter','none');
set(ax1,'XTick',fold_id,'XTickLabel',labels,'XLim',[0.45 5.55], ...
    'YLim',[0 0.82],'FontSize',7.6,'TickDir','out','Layer','top', ...
    'Box','off','XGrid','off','YGrid','on');
xlabel(ax1,'Outer depth fold','FontSize',8.5);
ylabel(ax1,'R²','FontSize',8.5);
title(ax1,'(a) Outer-fold R²','FontSize',9,'FontWeight','bold');

% Panel b: RMSE
ax2 = nexttile(tl,2);
bar(ax2,fold_id,rmse,0.62,'FaceColor',c.wellA, ...
    'EdgeColor',[0.12 0.25 0.36],'LineWidth',0.45);
hold(ax2,'on');
yline(ax2,D.cvPooledRMSE,'--','Color',[0.25 0.25 0.25], ...
    'LineWidth',1.0);
text(ax2,fold_id,rmse+0.0020,compose('%.4f',rmse), ...
    'HorizontalAlignment','center','VerticalAlignment','bottom', ...
    'FontSize',7.2,'FontWeight','bold','Interpreter','none');
text(ax2,0.58,0.096, ...
    sprintf('pooled RMSE = %.4f km/s',D.cvPooledRMSE), ...
    'HorizontalAlignment','left','VerticalAlignment','top', ...
    'FontSize',7.0,'Color',[0.20 0.20 0.20], ...
    'BackgroundColor','white','Margin',1.5,'Interpreter','none');
set(ax2,'XTick',fold_id,'XTickLabel',labels,'XLim',[0.45 5.55], ...
    'YLim',[0 0.10],'FontSize',7.6,'TickDir','out','Layer','top', ...
    'Box','off','XGrid','off','YGrid','on');
xlabel(ax2,'Outer depth fold','FontSize',8.5);
ylabel(ax2,'RMSE (km/s)','FontSize',8.5);
title(ax2,'(b) Outer-fold RMSE','FontSize',9,'FontWeight','bold');

nrr_assert_canonical(D);
drawnow;
nrr_export_figure(fig,out_dir,'FIG03_nested_cv');

result = struct('status',"PASS",'name',"FIG03_nested_cv", ...
    'png_path',fullfile(out_dir,'FIG03_nested_cv.png'), ...
    'pdf_path',fullfile(out_dir,'FIG03_nested_cv.pdf'), ...
    'fold_id',fold_id(:)','fold_n',nfold(:)', ...
    'r2',r2(:)','rmse',rmse(:)', ...
    'pooled_r2',D.cvPooledR2,'pooled_rmse',D.cvPooledRMSE);
close(fig);
end
