function [nets, ledger] = fit_base_set(X, y, hp, base_seed, fold_id, cfg)
% NRR_MODELS.FIT_BASE_SET  Fit all 4 base learners with per-model seeds.
%   Seed scheme (v4): seed = base_seed + offset_model + fold_id * offset_fold
%   No silent fallback to ridge_proxy — failure throws error.
%   Returns seed ledger for audit.

os = cfg.seeds;
seeds = struct(...
    'pnn',    base_seed + os.offset_pnn   + fold_id * os.offset_fold,...
    'mlffnn', base_seed + os.offset_mlffnn + fold_id * os.offset_fold,...
    'dffnn',  base_seed + os.offset_dffnn  + fold_id * os.offset_fold,...
    'cnn1d',  base_seed + os.offset_cnn1d  + fold_id * os.offset_fold);

% Build per-model HP structs from frozen hp
hp_pnn   = struct('spread', hp.pnn_spread);
hp_ml    = struct('hidden',hp.mlffnn_hidden,'lr',hp.mlffnn_lr,...
                  'epochs',hp.mlffnn_epochs,'batch',hp.mlffnn_batch);
hp_df    = struct('hidden',hp.dffnn_hidden,'lr',hp.dffnn_lr,...
                  'epochs',hp.dffnn_epochs,'batch',hp.dffnn_batch);
hp_cn    = struct('filters',hp.cnn1d_filters,'lr',hp.cnn1d_lr,...
                  'epochs',hp.cnn1d_epochs,'batch',hp.cnn1d_batch);

nets.pnn    = nrr_models.fit_pnn(X,y,hp_pnn,seeds.pnn,cfg);
nets.mlffnn = nrr_models.fit_mlffnn(X,y,hp_ml,seeds.mlffnn,cfg);
nets.dffnn  = nrr_models.fit_dffnn(X,y,hp_df,seeds.dffnn,cfg);
nets.cnn1d  = nrr_models.fit_cnn1d(X,y,hp_cn,seeds.cnn1d,cfg);

% Acceptance assertions — no ridge_proxy allowed
names={'pnn','mlffnn','dffnn','cnn1d'};
for ni=1:4
    nm=names{ni};
    assert(~strcmp(nets.(nm).type,'ridge_proxy'),...
        'fit_base_set: %s is ridge_proxy — training failure',nm);
    assert(strcmp(nets.(nm).type,nm),...
        'fit_base_set: %s model.type mismatch (%s)',nm,nets.(nm).type);
end

% Seed ledger
ledger=table(...
    {base_seed;base_seed;base_seed;base_seed},...
    names',...
    {seeds.pnn;seeds.mlffnn;seeds.dffnn;seeds.cnn1d},...
    {fold_id;fold_id;fold_id;fold_id},...
    'VariableNames',{'BASE_SEED','MODEL','DERIVED_SEED','FOLD_ID'});
end
