function [nets, ledger] = fit_base_set(X, y, hp, base_seed, fold_id, cfg, segment_ids)
% NRR_MODELS.FIT_BASE_SET  Fit four learners with mandatory CNN segments.
% No fallback to a single segment is permitted in corrected PED runs.

assert(nargin>=7 && ~isempty(segment_ids), ...
    'fit_base_set: segment_ids is mandatory');
assert(numel(segment_ids)==size(X,1), ...
    'fit_base_set: segment_ids length mismatch');
os=cfg.seeds;
seeds=struct('pnn',base_seed+os.offset_pnn+fold_id*os.offset_fold, ...
    'mlffnn',base_seed+os.offset_mlffnn+fold_id*os.offset_fold, ...
    'dffnn',base_seed+os.offset_dffnn+fold_id*os.offset_fold, ...
    'cnn1d',base_seed+os.offset_cnn1d+fold_id*os.offset_fold);

hp_pnn=struct('spread',hp.pnn_spread);
hp_ml=struct('hidden',hp.mlffnn_hidden,'lr',hp.mlffnn_lr, ...
    'epochs',hp.mlffnn_epochs,'batch',hp.mlffnn_batch);
hp_df=struct('hidden',hp.dffnn_hidden,'lr',hp.dffnn_lr, ...
    'epochs',hp.dffnn_epochs,'batch',hp.dffnn_batch);
hp_cn=struct('filters',hp.cnn1d_filters,'lr',hp.cnn1d_lr, ...
    'epochs',hp.cnn1d_epochs,'batch',hp.cnn1d_batch);

nets.pnn=nrr_models.fit_pnn(X,y,hp_pnn,seeds.pnn,cfg);
nets.mlffnn=nrr_models.fit_mlffnn(X,y,hp_ml,seeds.mlffnn,cfg);
nets.dffnn=nrr_models.fit_dffnn(X,y,hp_df,seeds.dffnn,cfg);
nets.cnn1d=nrr_models.fit_cnn1d(X,y,hp_cn,seeds.cnn1d,cfg,segment_ids);

names=["pnn";"mlffnn";"dffnn";"cnn1d"];
for ni=1:4
    assert(~strcmp(nets.(names(ni)).type,'ridge_proxy'), ...
        'fit_base_set: %s is ridge_proxy',names(ni));
    assert(strcmp(nets.(names(ni)).type,names(ni)), ...
        'fit_base_set: %s model.type mismatch',names(ni));
end

n_candidate=zeros(4,1); n_valid=zeros(4,1); n_discarded=zeros(4,1);
n_retained=zeros(4,1); n_segments=zeros(4,1);
n_candidate(4)=nets.cnn1d.n_candidate_windows;
n_valid(4)=nets.cnn1d.n_valid_windows;
n_discarded(4)=nets.cnn1d.n_discarded_cross_segment;
n_retained(4)=nets.cnn1d.n_retained_cross_segment;
n_segments(4)=numel(unique(segment_ids));
ledger=table(repmat(base_seed,4,1),names, ...
    [seeds.pnn;seeds.mlffnn;seeds.dffnn;seeds.cnn1d], ...
    repmat(fold_id,4,1),n_segments,n_candidate,n_valid,n_discarded,n_retained, ...
    repmat("PHYSICAL_DEPTH_SEGMENTS",4,1),nan(4,1),nan(4,1),zeros(4,1), ...
    'VariableNames',{'BASE_SEED','MODEL','DERIVED_SEED','FOLD_ID', ...
    'N_SEGMENTS','N_CANDIDATE_WINDOWS','N_VALID_WINDOWS', ...
    'N_DISCARDED_CROSS_SEGMENT','N_RETAINED_CROSS_SEGMENT','WINDOW_POLICY', ...
    'OUTER_FOLD','INNER_FOLD','PRED_RETAINED_CROSS_SEGMENT'});
assert(ledger.N_RETAINED_CROSS_SEGMENT(4)==0, ...
    'fit_base_set: retained cross-segment CNN window');
end
